### ISSUE TITLE
(Incorrect regex) gulp-tasks/git-hooks-install.js:6

### ISSUE THREAD

**Issue by spr1ne** [bradleygore/pre-commit-demo#1]
[gulp-tasks/git-hooks-install.js:6](https://github.com/bradleygore/pre-commit-demo/blob/b58e0dfb228e331e046d88783e8b57ccfbe9bc36/gulp-tasks/git-hooks-install.js#L6)

This will cause problems, on the mac. 
It's expected to use win32 platform, but for darwin it will work, too.

**Comment by bradleygore** [comment]
@Sweet-Bob - nice catch, thanks! Fixed in 2b0b07d
